### ISSUE TITLE
the example need more detail

### ISSUE THREAD

**Issue by tsingson** [RussellLuo/timingwheel#1]
great design for golang timing .
but, v need more detail in example code ...

thanks a lot.

**Comment by RussellLuo** [comment]
@tsingson By "more detail", you mean more comments, or more examples?

Maybe it's better to point out what was unclear :-)

**Comment by tsingson** [comment]
yet,   more then one example, like two task ( via may be two func ) in timingwhell.

thanks a lot for fast response.

**Comment by tsingson** [comment]
one more questions:    the timingwheel is thread safe ? how use this in goroutine:  init one global timingwheel only ?

**Comment by RussellLuo** [comment]
@tsingson I have updated the example a little.

For your second question, yes the TimingWheel is concurrency-safe, you only need one TimingWheel instance.

**Comment by RussellLuo** [comment]
The issue has been closed automatically after the new commit is pushed, feel free to reopen it if necessary :)
