### ISSUE TITLE
What is this chan used for?

### ISSUE THREAD

**Issue by andrewtw** [RussellLuo/timingwheel#16]
Hi there,

I'm quite confused about this line, https://github.com/RussellLuo/timingwheel/blob/f534fd34a76229c9db53193e394bf7e58982236b/delayqueue/delayqueue.go#L177.
After receiving the data from channel, it does nothing right?

But per your comment stated, it should send the expired element to wheel.
Can you please explain the usage?

Thank you!

**Comment by andrewtw** [comment]
I took some time and read your code carefully, now the problem is solved!

**Comment by RussellLuo** [comment]
The comments have been updated, see [here](https://github.com/RussellLuo/timingwheel/commit/0e67dbf0ae97e5cbdc37a19f2bfcdacb9873d19a) for details.

@andrewtw Thanks for your attention, any more advice is welcome!
