### ISSUE TITLE
不能支持根据 id 添加任务吗

### ISSUE THREAD

**Issue by JeffreyBool** [RussellLuo/timingwheel#21]
```go
t := tw.ScheduleFunc(&EveryScheduler{1,time.Second * 2}, func() {
		i++
		fmt.Println("The timer fires")
		fmt.Println(i)
		//exitC <- time.Now().UTC()
})
```

这种删除这个任务需要将 `t` 的指针保存下来，很不友好。感觉可以通过 id 的方式删除

**Comment by RussellLuo** [comment]
@JeffreyBool 如果想 “通过 id 的方式删除”，建议自己维护一个 `id -> timer` 的映射关系。

不同的需求有不同的用法。作为一个基础库，timingwheel 希望跟 [Go 标准库](https://golang.org/pkg/time/#AfterFunc) 一样，致力于提供通用的基础功能。

**Comment by JeffreyBool** [comment]
我觉得用id比反射结构体强------------------ 原始邮件 ------------------
发件人: "Luo Peng"<notifications@github.com>
发送时间: 2020年4月23日(星期四) 上午8:59
收件人: "RussellLuo/timingwheel"<timingwheel@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [RussellLuo/timingwheel] 不能支持根据 id 添加任务吗 (#21)




 
@JeffreyBool 如果想 “通过 id 的方式删除”，建议自己维护一个 id -> timer 的映射关系。
 
不同的需求有不同的用法。作为一个基础库，timingwheel 希望跟 Go 标准库 一样，致力于提供通用的基础功能。
 
&mdash;

**Comment by RussellLuo** [comment]
> 我觉得用id比反射结构体强

- “反射结构体” 是指前面你说的 timer 指针吗？
- 如果用 id 的话，能具体说下你的想法吗，比如 id 如何设计（类型和取值）？
