### ISSUE TITLE
时间轮对象可以重复使用么

### ISSUE THREAD

**Issue by jp3411952** [RussellLuo/timingwheel#22]
type EveryScheduler struct {
	Interval time.Duration
}

func (s *EveryScheduler) Next(prev time.Time) time.Time {
	return prev.Add(s.Interval)
}

func main() {
	tw := timingwheel.NewTimingWheel(time.Millisecond, 20)
	tw.Start()
	defer tw.Stop()
	
	t := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 200}, func() {
		fmt.Println("The timer fires 200",time.Now())
	})
	t2 := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 500}, func() {
		fmt.Println("The timer fires 500",time.Now())
	})
	
	fmt.Println("main")
	time.Sleep(time.Second * 10)
	t.Stop()
	t2.Stop()
}

**Comment by jp3411952** [comment]
ScheduleFunc 这个函数是一直调用直到stop哦

**Comment by RussellLuo** [comment]
@jp3411952 
- 关于 ScheduleFunc 的功能，可以参考下 [GoDoc](https://godoc.org/github.com/RussellLuo/timingwheel#TimingWheel.ScheduleFunc) 以及 [#11](https://github.com/RussellLuo/timingwheel/issues/11)。
- 你提到的 “时间轮对象可以重复使用么”，不太明白具体想如何复用？

**Comment by jp3411952** [comment]
t := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 200}, func() {
	fmt.Println("The timer fires 200",time.Now())
})
t2 := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 500}, func() {
	fmt.Println("The timer fires 500",time.Now())
})

**Comment by jp3411952** [comment]
如代码

**Comment by RussellLuo** [comment]
> t := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 200}, func() {
>     fmt.Println("The timer fires 200",time.Now())
> })
> t2 := tw.ScheduleFunc(&EveryScheduler{time.Millisecond * 500}, func() {
>     fmt.Println("The timer fires 500",time.Now())
> })

这段代码中，时间轮实例是 tw，定时器实例是 t/t2。

@jp3411952 时间轮实例 tw 已经是复用的了，你是想复用定时器实例吗？比如 “在 t2 处，希望直接把 t 从 200ms 改成 500ms”？
