### ISSUE TITLE
大佬,分层管理定时器在哪里实现的呢? 每个定时器都是一个协程处理哦？

### ISSUE THREAD

**Issue by jp3411952** [RussellLuo/timingwheel#23]

**Comment by RussellLuo** [comment]
> 分层管理定时器在哪里实现的呢?

高层时间轮是 **按需创建的**，关键代码在 [这里](https://github.com/RussellLuo/timingwheel/blob/0e67dbf0ae97e5cbdc37a19f2bfcdacb9873d19a/timingwheel.go#L89-L106)。（详细参考 [层级时间轮的 Golang 实现](http://russellluo.com/2018/10/golang-implementation-of-hierarchical-timing-wheels.html)）

> 每个定时器都是一个协程处理哦？

是的，这个处理方式是参考的 [AfterFunc](https://golang.org/pkg/time/#AfterFunc)。

**Comment by jp3411952** [comment]
好的，谢谢
