### ISSUE TITLE
bug of calculate expiration

### ISSUE THREAD

**Issue by mupengX** [RussellLuo/timingwheel#3]
the timingwheel add() 方法中：
```
else if t.expiration < tw.currentTime+tw.interval {
		// Put it into its own bucket
		virtualID := t.expiration / tw.tick
		b := tw.buckets[virtualID%tw.wheelSize]
		b.Add(t)

		// Set the bucket expiration time
		if b.SetExpiration(virtualID * tw.tick) {
			tw.queue.Offer(b)
		}

		return true
	}
```
求VirtualID应该是irtualID := (t.expiration - tw.currentTime +1)  / tw.tick ，b.SetExpiration(virtualID * tw.tick) 应该是b.SetExpiration(tw.currentTime + virtualID * tw.tick) 
```
func (tw *TimingWheel) advanceClock(expiration int64) {
	if expiration >= tw.currentTime+tw.tick {
		tw.currentTime = truncate(expiration, tw.tick)

		// Try to advance the clock of the overflow wheel if present
		overflowWheel := atomic.LoadPointer(&tw.overflowWheel)
		if overflowWheel != nil {
			(*TimingWheel)(overflowWheel).advanceClock(tw.currentTime)
		}
	}
}
```
advanceClock()中传入的是bucket. Expiration()，按照现在的逻辑bucket. Expiration()=virtualID * tw.tick，advanceClock()方法中的if语句应该是不会成立的。

**Comment by RussellLuo** [comment]
@mupengX 谢谢关注！timingwheel 参考了 Kafka 的实现，你指出的这些细节，Kafka 也是这样处理的。

你可以看看 [我的博文介绍](http://russellluo.com/2018/10/golang-implementation-of-hierarchical-timing-wheels.html#1-_时间轮表示) ，以及 Kafka 的源码（[这里](https://github.com/apache/kafka/blob/3cdc78e6bb1f83973a14ce1550fe3874f7348b05/core/src/main/scala/kafka/utils/timer/TimingWheel.scala#L134-L148) 和 [这里](https://github.com/apache/kafka/blob/3cdc78e6bb1f83973a14ce1550fe3874f7348b05/core/src/main/scala/kafka/utils/timer/TimingWheel.scala#L158-L165)）。

**Comment by mupengX** [comment]
是我开始理解错了，谢谢！
