### ISSUE TITLE
时间轮的大小的作用和选取

### ISSUE THREAD

**Issue by yangjuncode** [RussellLuo/timingwheel#4]
tick决定了分辨率,层级时间轮可以任意时间,那时间轮的大小的作用是什么? 选取有什么讲究吗?

**Comment by RussellLuo** [comment]
1. tick 的选取，取决于业务需要的「时间分辨率」
2. wheelSize 的选取：
    - 取决于两个因素：
      + 业务需要支持的「最大到期时间间隔」maxD
      + 定时任务的分布情况
    - 具体而言：
      + maxD = tick * wheelSize ^ N（tick 固定时，wheelSize 与「时间轮层级数」N 成反比）
        + wheelSize 太大，极端情况下参考 [博文](http://russellluo.com/2018/10/golang-implementation-of-hierarchical-timing-wheels.html) 中对 “简单时间轮” 的缺点描述
        + wheelSize 太小，「时间轮层级数」N 就会很大，如果有很多 “到期时间间隔较大” 的定时任务，那么这些任务就会被频繁 **降级**（从高层时间轮 reinsert 到低层时间轮），这些操作也是有代价的

**Comment by yangjuncode** [comment]
解释得很好,谢谢!
