### ISSUE TITLE
bucket Flush 中链表的删除操作导致多个相同的定时器只会被执行一个

### ISSUE THREAD

**Issue by wfireleaves** [RussellLuo/timingwheel#41]
golang 中，for循环从前往后删除list的元素是存在问题的，删除前边的会导致无法获取到Next，因此，在bucket的Flush方法中，可以调整成如下方式   
```golang
for e := b.timers.Front(); e != nil; {
	tmp := e.Next()
	t := e.Value.(*Timer)
	b.remove(t)
	ts = append(ts, t)
	e = tmp
}
```

**Comment by RussellLuo** [comment]
@wfireleaves 谢谢关注！当前 `bucket.Flush` 就是这样实现的：

https://github.com/RussellLuo/timingwheel/blob/54845bda31084d50d98d83afb01bd89d48154668/bucket.go#L118-L129

这个 issue 我先关闭了，有其他问题欢迎再反馈，谢谢！
